// Custom images for filter options
const filters = {
  actress: {
  "Minamo": "https://lh3.googleusercontent.com/d/13F5qz6Dg9EUA9_KI1nAeRsQ5fNK-nCFB",
  "Yatsugake Umi": "https://lh3.googleusercontent.com/d/13uZgn64wryobSTq7SMQMFyFV2hDA2QI4",
  "Yoshitaka Nene": "https://lh3.googleusercontent.com/d/13dd8yEZuzyx5Yj31yJIdUoefj2kygQeY",
  "Asano Kokoro": "https://lh3.googleusercontent.com/d/13TKLdkbxAkuw6a05esoPjV7G3FxqS_n8",
  "Miyajima Mei": "https://lh3.googleusercontent.com/d/14sQWLO4bcmDn-AlimVujYE2BKgoJbs4g",
  "Sakakihara Moe": "https://lh3.googleusercontent.com/d/13l9JhLM-pHwk9FS_PDll00AtdmebwPOL",
  "Shitara Yuuhi": "https://lh3.googleusercontent.com/d/13gQzdwUUMPDqsUjzSx9jaDoKaFw0_6-K",
  "Tachibana Mary": "https://lh3.googleusercontent.com/d/15_3vEPu0vITayCg3eJjOMXpUmpTcxpJI",
  "Kawakita Saika": "https://lh3.googleusercontent.com/d/13NLn5XnZV_KVRR7_EtUm6qbGn8Vqpp4w",
  "Kaede Karen": "https://lh3.googleusercontent.com/d/151tX4Xuuls3qzuZRgE7egZ5-Yc90o4oW",
  "Kodama Nanami": "https://lh3.googleusercontent.com/d/154RQeEbyraafSZDD6QKieXY2xELdz5nV",
  "Nanatsumori Riri": "https://lh3.googleusercontent.com/d/13OkczwZyXT01U9-jzV4B6zFTm0AFuiOy",
  "Miyashita Rena": "https://lh3.googleusercontent.com/d/154t2XiQic1erJ3V9omTC4rjbHFEHfE5h",
  "Itsukaichi Mei": "https://lh3.googleusercontent.com/d/1590aJAgYvZTQXafRLFQM8nPjBhXjFV3j",
  "Honjou Suzu": "https://lh3.googleusercontent.com/d/15CNd9Xf_5WoEU79_h6XoA2R6EUZfnlcM",
  "Miho Nana": "https://lh3.googleusercontent.com/d/157Yh1rZ_okPhbUt7WkCTd6W3PAalWj8N",
  "Sakura Norino": "https://lh3.googleusercontent.com/d/15Hru0i5O0KFPlD6S6YZ8fdE96i3L4SvP",
  "Hayasaka Hime": "https://lh3.googleusercontent.com/d/15QTFVxxBxBG340akHDdo4mxbTyi9zAFz",
  "Nonoura Non": "https://lh3.googleusercontent.com/d/15WIHB_pa-GfBHKxT4wdERvZzRr-b_UOR",
  "Arata Arina": "https://lh3.googleusercontent.com/d/15YTRCB6Rrgiv5uQMi6y9fY7YTPmOusJW",
  "Sakura Momo": "https://lh3.googleusercontent.com/d/160LlM224pxbY_7Kef3ptJmAmcTd29bqY",
  "Minami Aizawa": "https://lh3.googleusercontent.com/d/164sA3dmx52D9K8QVOUbS13ex76XupaMI",
  "Nosaka Hiyori": "https://lh3.googleusercontent.com/d/16URYYdIkjrGK83XQFETUjI7jaxlGNnqI",
  "Tokita Ami": "https://lh3.googleusercontent.com/d/16iFaPaDm2uF7ncZvVMjuZikb4T8smWWH",
  "Mori Ayami": "https://lh3.googleusercontent.com/d/17XfF4AxcIjxn54zC189Z4SrQFUhCIUmg",
  "Mochizuki Tsubomi": "https://lh3.googleusercontent.com/d/16o77GrSsKd335_lEj-jM4v6olq_sPJi3",
  "Suzunoya Rin": "https://lh3.googleusercontent.com/d/16l3devfyiGiiW0Pt4ftBCBFLqNIhb7M3",
  "Nijimura Yumi": "https://lh3.googleusercontent.com/d/1-SXJROKyfoBe1yQ_XjO3Glqlyb6N0Q-z",
  "Ashitaba Mitsuha": "https://lh3.googleusercontent.com/d/1-Z_293LnV7YAwoITP_tggvF953gVAd9q",
  "Sasaki Saki": "https://lh3.googleusercontent.com/d/1-RnpmNAMzN-m-gjJboHsVKkvk-ihi52X",
  "Miru": "https://lh3.googleusercontent.com/d/108EojxVxUborKqo7HxGoz6wUgA1pPmlJ",
  "Kudou Rara": "https://lh3.googleusercontent.com/d/10eqZpiePoI5_hjUsEZv-zTZDv8hXVydZ",
  "Kurumi Sakura": "https://lh3.googleusercontent.com/d/10lGxBXeHBZVSL4zFDfenNswDdSiSSuyh",
  "Nagisa Airi": "https://lh3.googleusercontent.com/d/10mOc4Gn5zJEJZ1mt2L44gehS8CHYW-P0",
  "Tsubasa Mai": "https://lh3.googleusercontent.com/d/10pfkl_-1PWK8_EiwQBRqaq-BaZCthvNu",
  "Kaede Fuua": "https://lh3.googleusercontent.com/d/10yqQ9iuMS-ZdGLTPdwm_Tfa4hZJ7-Rfl",
  "Ayumi Ryou": "https://lh3.googleusercontent.com/d/11-IYV7MYcv7MDp1cPKDNVTbVWEwVhdcc",
  "Yorimoto Shiori": "https://lh3.googleusercontent.com/d/115qSkdLb9UDGqy8-VoujfQ3wrM_Pe1D_",
  "Hinata Marin": "https://lh3.googleusercontent.com/d/11FQqEffRc3ZZiVAwnlnMB7GvdPVO98FT",
  "Amane Mahina": "https://lh3.googleusercontent.com/d/11O2uOJWZkC3f-VQ9XMpUz6WLaOr8uuNW",
  "Nanashima Mai": "https://lh3.googleusercontent.com/d/11rArnb4ZN2qnvoP5iquFi7o9uN7YJory",
  "Aoba Haru": "https://lh3.googleusercontent.com/d/11tJ_4Q51WvuXyi_5yq0zWkxNYc8-Ox-G",
  "Mio Mao": "https://lh3.googleusercontent.com/d/11wbiKXkNT0JnuwXjodJiDIvNjpx2CiNc",
  "Nagisa Mitsuki": "https://lh3.googleusercontent.com/d/121rT1vVIUSIGpVTFIkdCLJGWkOW1JQWe",
  "Shiromine Miu": "https://lh3.googleusercontent.com/d/124zq0am6yb5KczFRpUz-G6xDGc3eN3e4",
  "Momonogi Kana": "https://lh3.googleusercontent.com/d/12iehLsCmBjrbDzibTQwE_AuGFqwiHBEl",
  "Ichika Nenne": "https://lh3.googleusercontent.com/d/112e5i7r6OQrZANIkKN4LR54oXTvGOZZO",
  "Kosaka Nanaka": "https://lh3.googleusercontent.com/d/12phTVEuvBU1EXFbhSY4z99S_M0M4MQpd",
  "Irita Maaya": "https://lh3.googleusercontent.com/d/11VdSQy0KzHZ7R-NVg6zYtX89qMe6luf-",
  "Azusa Hikari": "https://lh3.googleusercontent.com/d/17Q5wRlvT0VEHF2iAFWLTHmaWcCLXVoeQ",
  "Kuroshima Rei": "https://lh3.googleusercontent.com/d/111i0fkxtQP7Dr34I22LFQMB0ilGIZGiC",
  "Akari Matsunaga": "https://lh3.googleusercontent.com/d/12qILO-84ZMyGVqOIo9O9yQ3lRmxNTCVs",
  "Mito Kana": "https://lh3.googleusercontent.com/d/12vao9oAL-tRtN4J_MnnO-5JdsbEIrxGj",
  "Jinguji Nao": "https://lh3.googleusercontent.com/d/13WwYomyqb7gpuqO2rjuUm6fJxBCjLBdE",
  "Mikami Yua": "https://lh3.googleusercontent.com/d/163Ehim2T7JDp8BSuw4gY1vu8AfLhyAs2",
  "Yuzuriha Karen": "https://lh3.googleusercontent.com/d/13aMNnpld-t2NaJqsPM0-admugKjlY-fc",
  "Hongou Ai": "https://lh3.googleusercontent.com/d/13nCLgHgEX8MivRYN0jEHfbMxDlCWH-0c",
  "Suzumori Remu": "https://lh3.googleusercontent.com/d/13oGLTd9Hm9-sOZxFHxpEgXziH2MurX0j"
},
  studio: {
    "Studio X": "https://via.placeholder.com/200x300.png?text=Studio+X",
    "Studio Y": "https://yourcdn.com/studioY.jpg"
  },
  label: {
    "Label 1": "https://via.placeholder.com/200x300.png?text=Label+1",
    "Label 2": "https://yourcdn.com/label2.jpg"
  },
  series: {
    "Series 1": "https://via.placeholder.com/200x300.png?text=Series+1",
    "Series 2": "https://yourcdn.com/series2.jpg"
  },
  tags: {
    "Tag1": "https://via.placeholder.com/200x300.png?text=Tag1",
    "Tag2": "https://yourcdn.com/tag2.png",
    "Tag3": "https://yourcdn.com/tag3.png"
  }
};
